#!/usr/bin/env node

(function () {
  const a = require.resolve.paths("@byted/rrp-sdk");
  console.log(a);
  const getConfig = require("./utils/getConfig")();
  const Cover = require("./cover");
  const coverInstant = new Cover(getConfig);
  coverInstant.getEffectScopeData();
})();
